// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqnaduERtz7to6gcTJ8Y_K2xt19iX-qYM',
    appId: '1:522568675021:web:5e6514ed495a6e01630384',
    messagingSenderId: '522568675021',
    projectId: 'sleshaproject',
    authDomain: 'sleshaproject.firebaseapp.com',
    storageBucket: 'sleshaproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXZnIIQ3z0CQih5kchUg7zbklafgXkaqk',
    appId: '1:522568675021:android:3221aee28b9390c4630384',
    messagingSenderId: '522568675021',
    projectId: 'sleshaproject',
    storageBucket: 'sleshaproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5IWp0alNhUX1wfvV4WJqS3Pgz-WqNpTk',
    appId: '1:522568675021:ios:2eb1c39880c1f135630384',
    messagingSenderId: '522568675021',
    projectId: 'sleshaproject',
    storageBucket: 'sleshaproject.appspot.com',
    iosClientId: '522568675021-pasuojs6e5bl25h06s1nq08cshcj59ac.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );
}
